
Vagrant.configure("2") do |config|
  
    config.vm.define "ansible-controller" do |controller|
    controller.vm.hostname = "controller"
    end
    config.vm.box = "centos/7"
    config.vm.provision "shell", inline: <<-SHELL
    SHELL

  end
