Vagrant.configure("2") do |config|
  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/buster64"
    debian.vm.hostname = "debian"
    debian.vm.network "private_network", ip: "192.168.33.10"
    debian.vm.provision "shell", path: "install_docker.sh"
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "private_network", ip: "192.168.33.11"
    ubuntu.vm.provision "shell", path: "install_docker.sh"
  end

  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "generic/fedora32"
    fedora.vm.hostname = "fedora"
    fedora.vm.network "private_network", ip: "192.168.33.12"
    fedora.vm.provision "shell", path: "install_docker.sh"
  end
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  config.vm.usable_port_range = (8000..9000)
end


